import Image from "next/image";
import { ArrowUpRight, AudioLines, Cable, Headphones, Monitor, Radio, Truck, Wrench } from "lucide-react";
import { Header } from "./components/Header";
import { Hero } from "./components/Hero";
import { ProductCatalog } from "./components/ProductCatalog";
import { PackagesSection } from "./components/PackagesSection";
import { ContactButton, ContactProvider } from "./components/ContactProvider";
const faqs = [
  ["Түрээслэхийн тулд хэрхэн захиалга өгөх вэ?", "Сонирхсон төхөөрөмж эсвэл багцынхаа “Лавлах” товчийг дарж бидэнтэй холбогдоорой. Арга хэмжээний огноо, байршил, хэрэгцээг тань ярилцаж, үнийн санал болон боломжит төхөөрөмжийг тодруулна."],
  ["Түрээсийн үнэ хэрхэн тооцогдох вэ?", "Төхөөрөмжийн төрөл, тоо ширхэг, ашиглах хугацаа, байршил болон инженерийн үйлчилгээ шаардлагатай эсэхээс хамаарч үнийн санал гаргана."],
  ["Хүргэлт, суурилуулалт хийдэг үү?", "Хүргэлт, суурилуулалт болон арга хэмжээний өмнөх техникийн тестийг хэрэгцээнд тань тохируулж төлөвлөнө. Байршил, орох цаг, заалны нөхцөлөө урьдчилан хэлээрэй."],
  ["Ямар төхөөрөмж хэрэгтэйгээ мэдэхгүй байвал яах вэ?", "Арга хэмжээний төрөл, оролцогчдын тоо, заалны хэмжээ болон хөтөлбөрөө бидэнд хэлэхэд болно. Танд тохирох дуу, дүрс болон бусад техникийн шийдлийг хамт сонгоно."],
  ["Техникийн инженер ажиллуулах боломжтой юу?", "Арга хэмжээний үеийн техникийн дэмжлэгийг үйлчилгээний хүрээнд тохиролцож болно. Хөтөлбөр, үргэлжлэх хугацаагаа урьдчилан хуваалцаарай."],
];
export default function HomePage() {
  return <ContactProvider><a className="skip-link" href="#equipment">Үндсэн агуулга руу</a><Header /><main><Hero />
    <div className="specialties"><div className="container specialties-inner">{[[AudioLines, "AUDIO", "Тод дуугаралт"], [Monitor, "VISUAL", "Төгс дүрслэл"], [Headphones, "INTERPRETATION", "Хэлний хязгааргүй"], [Radio, "LIVE SOLUTIONS", "Хаанаас ч холбогдъё"]].map(([Icon, title, description]) => { const IconComponent = Icon as typeof AudioLines; return <div className="specialty" key={String(title)}><IconComponent size={25} strokeWidth={1.4} /><div><strong>{String(title)}</strong><span>{String(description)}</span></div></div>; })}</div></div>
    <ProductCatalog /><PackagesSection />
    <section className="section about-section" id="about"><div className="container about-grid"><div className="about-brand"><Image src="/interpro.jpeg" alt="INTERPRO — Audio Visual, Interpretation, Live Solutions" width={1004} height={650} /><div className="about-brand-caption"><span>THE PEOPLE BEHIND THE TECHNOLOGY</span><AudioLines size={24} /></div></div><div className="about-copy"><span className="eyebrow">03 / WHY INTERPRO</span><h2>Та арга хэмжээндээ.<br />Бид техникт нь.</h2><p>Сайн арга хэмжээний ард зөв төлөвлөлт, найдвартай холболт, нарийн тохиргоо байдаг. INTERPRO таны санааг бодит дуу, дүрс, холбоос болгоход тусална.</p><div className="service-list">{[{ icon: Truck, title: "Хүргэлт & суурилуулалт", text: "Төхөөрөмжийг байршилд хүргэж, ажиллахад бэлэн болгоно." }, { icon: Cable, title: "Холболт & урьдчилсан тест", text: "Дуу, дүрс, холболтыг эхлэхээс өмнө хамтад нь шалгана." }, { icon: Wrench, title: "Техникийн дэмжлэг", text: "Хөтөлбөрт тохирсон инженерийн оролцоог төлөвлөнө." }].map(service => <div className="service-item" key={service.title}><span className="service-icon"><service.icon size={21} /></span><div><h3>{service.title}</h3><p>{service.text}</p></div></div>)}</div></div></div></section>
    <section className="section process-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">04 / HOW IT WORKS</span><h2>Энгийн, эхнээс нь дуустал.</h2></div><p>Таны санаанаас арга хэмжээний өдөр хүртэл.</p></div><div className="process-grid">{[{ title: "Хэрэгцээгээ хуваалцах", text: "Арга хэмжээний төрөл, огноо, байршлаа бидэнд хэлээрэй." }, { title: "Шийдлээ тохирох", text: "Төхөөрөмж, үйлчилгээний хүрээ болон үнийн саналаа ярилцана." }, { title: "Бид бэлэн болгоно", text: "Тохирсон цагт хүргэж, суурилуулж, техникийн тест хийнэ." }].map((step, index) => <article className="process-step" key={step.title}><div className="step-top"><span>0{index + 1}</span><ArrowUpRight size={22} /></div><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></div></section>
    <section className="section faq-section" id="faq"><div className="container faq-grid"><div><span className="eyebrow">05 / GOOD TO KNOW</span><h2>Танд хэрэгтэй<br />хариултууд.</h2><p>Өөр асуулт байна уу? Бидэнтэй ярилцаарай.</p><ContactButton className="text-button">Холбоо барих <ArrowUpRight size={18} /></ContactButton></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span className="faq-plus" aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="contact-section" id="contact"><div className="container"><div className="contact-banner"><div><span className="eyebrow">YOUR NEXT EVENT STARTS HERE</span><h2>Дараагийн эвентээ<br />хамтдаа бүтээе.</h2><p>Танд хэрэгтэй техникийн шийдэл эндээс эхэлнэ.</p></div><ContactButton className="button button-dark">Бидэнтэй холбогдох <ArrowUpRight size={20} /></ContactButton><AudioLines className="contact-decoration" aria-hidden="true" /></div></div></section>
  </main><footer className="site-footer"><div className="container"><div className="footer-main"><div><a href="#home" className="footer-wordmark">INTERPRO<span>®</span></a><p>Audio Visual · Interpretation · Live Solutions</p></div><nav aria-label="Хөл хэсгийн цэс"><a href="#equipment">Төхөөрөмж</a><a href="#solutions">Шийдлүүд</a><a href="#about">Бидний тухай</a><a href="#contact">Холбоо барих</a></nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} INTERPRO. Бүх эрх хуулиар хамгаалагдсан.</span><span>САЙН ЭВЕНТ. ЗӨВ ШИЙДЭЛ.</span></div></div></footer><div className="mobile-contact-bar"><span><i />Эвентээ хамт төлөвлөе</span><ContactButton className="button button-lime">Холбогдох <ArrowUpRight size={17} /></ContactButton></div></ContactProvider>;
}
